name: plant_disease_detector
description: Plant disease detection app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5  # Use older version compatible with SDK 35
  image_picker: ^1.0.7
  tflite_flutter: ^0.11.0
  provider: ^6.1.2
  path_provider: ^2.1.4
  path: ^1.9.0
  image: ^4.1.7
  permission_handler: ^11.3.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/plant_disease_classifier.tflite
    - assets/models/plant_disease_segmentation.tflite
